import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <nav className="nav">
          <ul className="nav-list">
            <li>
              <a href="#">Home</a>
            </li>
            <li>
              <a href="#services">Services</a>
            </li>
          </ul>
        </nav>

        <section className="w-full">
          <div className="w-full h-[450px] relative">
            <Image src="/background.jpg" alt="electric " fill={true} />

            <div
              className="flex flex-col gap-[25px] top-[28%] left-[50%] translate-x-[-50%] absolute p-[25px]"
              style={{
                background:
                  "linear-gradient(rgba(0, 0, 0, 0.2),rgba(0, 0, 0, 0.2))",
              }}
            >
              <h1 className="text-[#FFF] whitespace-nowrap">
                Electric Controller
              </h1>
              <p className="text-[30px]">Mobile: 3476165341</p>
              <p className="text-[30px]">Email: giorgiloladze88@gmail.com</p>
            </div>
          </div>
        </section>

        <section class="projects-section">
          <h2 class="projects-section-header">Services</h2>

          <div class="projects-grid">
            <div class="project project-tile cursor-pointer">
              <img
                class="project-image"
                src="https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSELVHUzEjG8jUA1oMoH27yN0uYMCLefMQbeQ&usqp=CAU"
                alt="car key programming"
              />
              <p class="project-title">
                <span class="code">&lt;</span>
                Car Key Programming
                <span class="code">&#47;&gt;</span>
              </p>
            </div>
            <div class="project project-tile cursor-pointer">
              <img
                class="project-image"
                src="https://www.monsterinsights.com/wp-content/uploads/2019/11/breathtaking-online-shopping-statistics-you-never-knew.png"
                alt=" house electrician"
              />
              <p class="project-title">
                <span class="code">&lt;</span>
                House Electrician
                <span class="code">&#47;&gt;</span>
              </p>
            </div>
            <div class="project project-tile cursor-pointer">
              <img
                class="project-image"
                src="https://miro.medium.com/max/1024/1*zgL7m9aVUhlBUhCrHKy2QQ.jpeg"
                alt="security systems"
              />
              <p class="project-title">
                <span class="code">&lt;</span>
                Security Systems
                <span class="code">&#47;&gt;</span>
              </p>
            </div>
          </div>
        </section>
      </main>
    </>
  );
}
